@startuml Klassediagram

skinparam ClassAttributeIconSize 0

class Event_Manager {
    + em_queueUp : Int[*]
    + em_queueDown : Int[*]
    + em_nextFloor : Int
    + em_currentFloor : Int
    + em_clear()
    + em_checkButtonPressed()
    + em_getCurrentFloor() : Int
    + em_getNextFloor() : Int
    + em_clearCurrentFloor()
    + em_updateQueues()
    + em_printQueues()
}

class Tilstandsmaskin {
    - state
    - elevio_init()
    + motorDirection: Int
    + state_startUp()
    + state_stationary() : Int
    + state_move() : Int
    + state_openDoor() : Int
}

class Aktuator {
    + MotorDirection : enum[3]
    + elevio_motorDirection(dirn: MotorDirection)
    + mDirUp()
    + mDirDown()
    + mDirStop()
}

class Elevator{
    - main()
}

class Sensorer{
    + elevio_floorSensor(): int
    + elevio_stopButton(): int
    + elevio_obstruction(): int
}

class Timer{
    - t_start : clock_t
    - t_end : clock_t
    - timer_getTime() : Double
    + timer_start()
    + timer_isTimeOut() : Int
}

class Lys{
    + N_FLOORS : int = 4
    + elevio_buttonLamp(floor: int, button: ButtonType, value: int)
    + elevio_floorIndicator(floor: int)
    + elevio_doorOpenLamp(value: int)
    + elveio_stopLamp(value: int)
    + lights_floorOffCurrent(em_currentFloor: int*)
    + lights_floorOffAll()
}

class Etasje_Knapp{
    + ButtonType : enum[3]
    + N_BUTTONS : int = 3
    + elevio_callButton(floor: int, button: ButtonType) : int
}

Tilstandsmaskin <-- Event_Manager 

Aktuator -> Tilstandsmaskin
Aktuator --> Event_Manager

Tilstandsmaskin <- Lys

Event_Manager <- Etasje_Knapp
Lys <-- Etasje_Knapp

Timer --> Tilstandsmaskin
Sensorer --> Tilstandsmaskin
Elevator --> Tilstandsmaskin

@enduml